name: Flutter Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - name: Install dependencies
        run: flutter pub get

      - name: List Flutter Devices (for debugging)
        run: flutter devices

      # Set up Android Emulator and run integration tests
      - name: Run integration tests on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel
          script: flutter drive --driver=test_driver/main_test.dart --target=integration_test/app_flow_test.dart
          emulator-options: -no-window -no-audio -no-snapshot
