name: Flutter Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3" # or your Flutter version

      - name: Install dependencies
        run: flutter pub get

      # Set up Android SDK and Emulator
      - name: Setup Android SDK
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel
          script: flutter test integration_test
          emulator-options: -no-window -no-audio -no-snapshot


